export const REQUEST_ROBOTS_PENDING = 'REQUEST_ROBOTS_PENDING';
export const REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS';
export const REQUEST_ROBOTS_FAILED = 'REQUEST_ROBOTS_FAILED';
export const FILTER_ROBOTS = 'FILTER_ROBOTS';
export const TOGGLE_FAMILY_CHECKBOX = 'TOGGLE_FAMILY_CHECKBOX';

